/*
** Copyright (C) 1995-2005 Hewlett-Packard Company.
*/

/*
** You can redistribute this file it and/or modify it under the terms 
** of the GNU Library General Public License as published by the Free 
** Software Foundation; either version 2 of the License, or (at your 
** option) any later version.
**
** You should have received a copy of the GNU Library General Public
** License along with the GNU C Library; see the file COPYING.LIB.  If not,
** write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
** Boston, MA 02111-1307, USA.
*/

/********************************************/
/*         SYSTEM HEADER                    */
/********************************************/
/* $Id */

extern int sim_mem_probe(volatile unsigned int);
extern unsigned int sim_mem_access32(volatile unsigned int);
extern unsigned short sim_mem_access16(volatile unsigned int);
extern unsigned char sim_mem_access8(volatile unsigned int);
extern unsigned long long sim_cycle_counter;
extern unsigned long long sim_stall_counter;
extern unsigned long long sim_branch_stall;
extern unsigned long long sim_bundle_index[];
extern unsigned long long sim_oper_counter;
extern unsigned long long sim_bnt_counter;
extern unsigned long long sim_btc_counter;
extern unsigned long long sim_btu_counter;
extern unsigned long long sim_nop_counter;
extern unsigned int mem_trace_ld(unsigned int, unsigned int, unsigned int);
extern unsigned int mem_trace_st(unsigned int, unsigned int, unsigned int);
extern unsigned int mem_trace_pf(unsigned int, unsigned int, unsigned int);
extern unsigned int mem_trace_lds(unsigned int, unsigned int, unsigned int);
extern unsigned int mem_trace_sts(unsigned int, unsigned int, unsigned int);
extern unsigned int mem_trace_pfs(unsigned int, unsigned int, unsigned int);
extern void sim_ta_init(int);
extern void sim_ta_finish(void);
#define INC_STALL_CNT()		/* empty */
#define INC_BNT_CNT()		/* empty */
#define INC_BTC_CNT()		/* empty */
#define INC_BTU_CNT()		/* empty */
#define INC_NOP_CNT(n)		/* empty */
#define INC_BUNDLE_CNT(index)	/* empty */
#define ADD_CYCLES(cycles)	/* empty */

typedef struct
{
    char *name;
    int length;
    int init;
    int offset;
    int linesize;
    int rta;
} sim_fileinfo_t;

extern int sim_init_fileinfo(sim_fileinfo_t *);
extern void sim_icache_fetch(int, int);
extern void sim_gprof_enter(int *, char *f);
extern void sim_gprof_start(int *);
extern void sim_gprof_stop(int *);
extern void sim_gprof_exit(int *);

/*********************************
            BSS SYMBOLS
*********************************/

/*********************************
            ENTRY SYMBOLS
*********************************/

/*********************************
            DATA SYMBOLS
*********************************/

/*********************************
            TEXT
*********************************/
extern unsigned int sim_create_stack(unsigned int, unsigned int);
extern void sim_check_stack(unsigned int, unsigned int);
extern void sim_bad_label(int);
extern unsigned int reg_b0_0;
extern unsigned int reg_b0_1;
extern unsigned int reg_b0_2;
extern unsigned int reg_b0_3;
extern unsigned int reg_b0_4;
extern unsigned int reg_b0_5;
extern unsigned int reg_b0_6;
extern unsigned int reg_b0_7;
extern unsigned int reg_b0_8;
extern unsigned int reg_b0_9;
extern unsigned int reg_b0_10;
extern unsigned int reg_b0_11;
extern unsigned int reg_b0_12;
extern unsigned int reg_b0_13;
extern unsigned int reg_b0_14;
extern unsigned int reg_b0_15;
extern unsigned int reg_b1_0;
extern unsigned int reg_b1_1;
extern unsigned int reg_b1_2;
extern unsigned int reg_b1_3;
extern unsigned int reg_b1_4;
extern unsigned int reg_b1_5;
extern unsigned int reg_b1_6;
extern unsigned int reg_b1_7;
extern unsigned int reg_b1_8;
extern unsigned int reg_b1_9;
extern unsigned int reg_b1_10;
extern unsigned int reg_b1_11;
extern unsigned int reg_b1_12;
extern unsigned int reg_b1_13;
extern unsigned int reg_b1_14;
extern unsigned int reg_b1_15;
extern unsigned int reg_b2_0;
extern unsigned int reg_b2_1;
extern unsigned int reg_b2_2;
extern unsigned int reg_b2_3;
extern unsigned int reg_b2_4;
extern unsigned int reg_b2_5;
extern unsigned int reg_b2_6;
extern unsigned int reg_b2_7;
extern unsigned int reg_b2_8;
extern unsigned int reg_b2_9;
extern unsigned int reg_b2_10;
extern unsigned int reg_b2_11;
extern unsigned int reg_b2_12;
extern unsigned int reg_b2_13;
extern unsigned int reg_b2_14;
extern unsigned int reg_b2_15;
extern unsigned int reg_b3_0;
extern unsigned int reg_b3_1;
extern unsigned int reg_b3_2;
extern unsigned int reg_b3_3;
extern unsigned int reg_b3_4;
extern unsigned int reg_b3_5;
extern unsigned int reg_b3_6;
extern unsigned int reg_b3_7;
extern unsigned int reg_b3_8;
extern unsigned int reg_b3_9;
extern unsigned int reg_b3_10;
extern unsigned int reg_b3_11;
extern unsigned int reg_b3_12;
extern unsigned int reg_b3_13;
extern unsigned int reg_b3_14;
extern unsigned int reg_b3_15;
extern unsigned int reg_l0_0;
extern unsigned int reg_r0_0;
extern unsigned int reg_r0_1;
extern unsigned int reg_r0_2;
extern unsigned int reg_r0_3;
extern unsigned int reg_r0_4;
extern unsigned int reg_r0_5;
extern unsigned int reg_r0_6;
extern unsigned int reg_r0_7;
extern unsigned int reg_r0_8;
extern unsigned int reg_r0_9;
extern unsigned int reg_r0_10;
extern unsigned int reg_r0_11;
extern unsigned int reg_r0_12;
extern unsigned int reg_r0_13;
extern unsigned int reg_r0_14;
extern unsigned int reg_r0_15;
extern unsigned int reg_r0_16;
extern unsigned int reg_r0_17;
extern unsigned int reg_r0_18;
extern unsigned int reg_r0_19;
extern unsigned int reg_r0_20;
extern unsigned int reg_r0_21;
extern unsigned int reg_r0_22;
extern unsigned int reg_r0_23;
extern unsigned int reg_r0_24;
extern unsigned int reg_r0_25;
extern unsigned int reg_r0_26;
extern unsigned int reg_r0_27;
extern unsigned int reg_r0_28;
extern unsigned int reg_r0_29;
extern unsigned int reg_r0_30;
extern unsigned int reg_r0_31;
extern unsigned int reg_r0_32;
extern unsigned int reg_r0_33;
extern unsigned int reg_r0_34;
extern unsigned int reg_r0_35;
extern unsigned int reg_r0_36;
extern unsigned int reg_r0_37;
extern unsigned int reg_r0_38;
extern unsigned int reg_r0_39;
extern unsigned int reg_r0_40;
extern unsigned int reg_r0_41;
extern unsigned int reg_r0_42;
extern unsigned int reg_r0_43;
extern unsigned int reg_r0_44;
extern unsigned int reg_r0_45;
extern unsigned int reg_r0_46;
extern unsigned int reg_r0_47;
extern unsigned int reg_r0_48;
extern unsigned int reg_r0_49;
extern unsigned int reg_r0_50;
extern unsigned int reg_r0_51;
extern unsigned int reg_r0_52;
extern unsigned int reg_r0_53;
extern unsigned int reg_r0_54;
extern unsigned int reg_r0_55;
extern unsigned int reg_r0_56;
extern unsigned int reg_r0_57;
extern unsigned int reg_r0_58;
extern unsigned int reg_r0_59;
extern unsigned int reg_r0_60;
extern unsigned int reg_r0_61;
extern unsigned int reg_r0_62;
extern unsigned int reg_r0_63;
extern unsigned int reg_r0_64;
extern unsigned int reg_r0_65;
extern unsigned int reg_r0_66;
extern unsigned int reg_r0_67;
extern unsigned int reg_r0_68;
extern unsigned int reg_r0_69;
extern unsigned int reg_r0_70;
extern unsigned int reg_r0_71;
extern unsigned int reg_r0_72;
extern unsigned int reg_r0_73;
extern unsigned int reg_r0_74;
extern unsigned int reg_r0_75;
extern unsigned int reg_r0_76;
extern unsigned int reg_r0_77;
extern unsigned int reg_r0_78;
extern unsigned int reg_r0_79;
extern unsigned int reg_r0_80;
extern unsigned int reg_r0_81;
extern unsigned int reg_r0_82;
extern unsigned int reg_r0_83;
extern unsigned int reg_r0_84;
extern unsigned int reg_r0_85;
extern unsigned int reg_r0_86;
extern unsigned int reg_r0_87;
extern unsigned int reg_r0_88;
extern unsigned int reg_r0_89;
extern unsigned int reg_r0_90;
extern unsigned int reg_r0_91;
extern unsigned int reg_r0_92;
extern unsigned int reg_r0_93;
extern unsigned int reg_r0_94;
extern unsigned int reg_r0_95;
extern unsigned int reg_r0_96;
extern unsigned int reg_r0_97;
extern unsigned int reg_r0_98;
extern unsigned int reg_r0_99;
extern unsigned int reg_r0_100;
extern unsigned int reg_r0_101;
extern unsigned int reg_r0_102;
extern unsigned int reg_r0_103;
extern unsigned int reg_r0_104;
extern unsigned int reg_r0_105;
extern unsigned int reg_r0_106;
extern unsigned int reg_r0_107;
extern unsigned int reg_r0_108;
extern unsigned int reg_r0_109;
extern unsigned int reg_r0_110;
extern unsigned int reg_r0_111;
extern unsigned int reg_r0_112;
extern unsigned int reg_r0_113;
extern unsigned int reg_r0_114;
extern unsigned int reg_r0_115;
extern unsigned int reg_r0_116;
extern unsigned int reg_r0_117;
extern unsigned int reg_r0_118;
extern unsigned int reg_r0_119;
extern unsigned int reg_r0_120;
extern unsigned int reg_r0_121;
extern unsigned int reg_r0_122;
extern unsigned int reg_r0_123;
extern unsigned int reg_r0_124;
extern unsigned int reg_r0_125;
extern unsigned int reg_r0_126;
extern unsigned int reg_r0_127;
extern unsigned int reg_r1_0;
extern unsigned int reg_r1_1;
extern unsigned int reg_r1_2;
extern unsigned int reg_r1_3;
extern unsigned int reg_r1_4;
extern unsigned int reg_r1_5;
extern unsigned int reg_r1_6;
extern unsigned int reg_r1_7;
extern unsigned int reg_r1_8;
extern unsigned int reg_r1_9;
extern unsigned int reg_r1_10;
extern unsigned int reg_r1_11;
extern unsigned int reg_r1_12;
extern unsigned int reg_r1_13;
extern unsigned int reg_r1_14;
extern unsigned int reg_r1_15;
extern unsigned int reg_r1_16;
extern unsigned int reg_r1_17;
extern unsigned int reg_r1_18;
extern unsigned int reg_r1_19;
extern unsigned int reg_r1_20;
extern unsigned int reg_r1_21;
extern unsigned int reg_r1_22;
extern unsigned int reg_r1_23;
extern unsigned int reg_r1_24;
extern unsigned int reg_r1_25;
extern unsigned int reg_r1_26;
extern unsigned int reg_r1_27;
extern unsigned int reg_r1_28;
extern unsigned int reg_r1_29;
extern unsigned int reg_r1_30;
extern unsigned int reg_r1_31;
extern unsigned int reg_r1_32;
extern unsigned int reg_r1_33;
extern unsigned int reg_r1_34;
extern unsigned int reg_r1_35;
extern unsigned int reg_r1_36;
extern unsigned int reg_r1_37;
extern unsigned int reg_r1_38;
extern unsigned int reg_r1_39;
extern unsigned int reg_r1_40;
extern unsigned int reg_r1_41;
extern unsigned int reg_r1_42;
extern unsigned int reg_r1_43;
extern unsigned int reg_r1_44;
extern unsigned int reg_r1_45;
extern unsigned int reg_r1_46;
extern unsigned int reg_r1_47;
extern unsigned int reg_r1_48;
extern unsigned int reg_r1_49;
extern unsigned int reg_r1_50;
extern unsigned int reg_r1_51;
extern unsigned int reg_r1_52;
extern unsigned int reg_r1_53;
extern unsigned int reg_r1_54;
extern unsigned int reg_r1_55;
extern unsigned int reg_r1_56;
extern unsigned int reg_r1_57;
extern unsigned int reg_r1_58;
extern unsigned int reg_r1_59;
extern unsigned int reg_r1_60;
extern unsigned int reg_r1_61;
extern unsigned int reg_r1_62;
extern unsigned int reg_r1_63;
extern unsigned int reg_r1_64;
extern unsigned int reg_r1_65;
extern unsigned int reg_r1_66;
extern unsigned int reg_r1_67;
extern unsigned int reg_r1_68;
extern unsigned int reg_r1_69;
extern unsigned int reg_r1_70;
extern unsigned int reg_r1_71;
extern unsigned int reg_r1_72;
extern unsigned int reg_r1_73;
extern unsigned int reg_r1_74;
extern unsigned int reg_r1_75;
extern unsigned int reg_r1_76;
extern unsigned int reg_r1_77;
extern unsigned int reg_r1_78;
extern unsigned int reg_r1_79;
extern unsigned int reg_r1_80;
extern unsigned int reg_r1_81;
extern unsigned int reg_r1_82;
extern unsigned int reg_r1_83;
extern unsigned int reg_r1_84;
extern unsigned int reg_r1_85;
extern unsigned int reg_r1_86;
extern unsigned int reg_r1_87;
extern unsigned int reg_r1_88;
extern unsigned int reg_r1_89;
extern unsigned int reg_r1_90;
extern unsigned int reg_r1_91;
extern unsigned int reg_r1_92;
extern unsigned int reg_r1_93;
extern unsigned int reg_r1_94;
extern unsigned int reg_r1_95;
extern unsigned int reg_r1_96;
extern unsigned int reg_r1_97;
extern unsigned int reg_r1_98;
extern unsigned int reg_r1_99;
extern unsigned int reg_r1_100;
extern unsigned int reg_r1_101;
extern unsigned int reg_r1_102;
extern unsigned int reg_r1_103;
extern unsigned int reg_r1_104;
extern unsigned int reg_r1_105;
extern unsigned int reg_r1_106;
extern unsigned int reg_r1_107;
extern unsigned int reg_r1_108;
extern unsigned int reg_r1_109;
extern unsigned int reg_r1_110;
extern unsigned int reg_r1_111;
extern unsigned int reg_r1_112;
extern unsigned int reg_r1_113;
extern unsigned int reg_r1_114;
extern unsigned int reg_r1_115;
extern unsigned int reg_r1_116;
extern unsigned int reg_r1_117;
extern unsigned int reg_r1_118;
extern unsigned int reg_r1_119;
extern unsigned int reg_r1_120;
extern unsigned int reg_r1_121;
extern unsigned int reg_r1_122;
extern unsigned int reg_r1_123;
extern unsigned int reg_r1_124;
extern unsigned int reg_r1_125;
extern unsigned int reg_r1_126;
extern unsigned int reg_r1_127;
extern unsigned int reg_r2_0;
extern unsigned int reg_r2_1;
extern unsigned int reg_r2_2;
extern unsigned int reg_r2_3;
extern unsigned int reg_r2_4;
extern unsigned int reg_r2_5;
extern unsigned int reg_r2_6;
extern unsigned int reg_r2_7;
extern unsigned int reg_r2_8;
extern unsigned int reg_r2_9;
extern unsigned int reg_r2_10;
extern unsigned int reg_r2_11;
extern unsigned int reg_r2_12;
extern unsigned int reg_r2_13;
extern unsigned int reg_r2_14;
extern unsigned int reg_r2_15;
extern unsigned int reg_r2_16;
extern unsigned int reg_r2_17;
extern unsigned int reg_r2_18;
extern unsigned int reg_r2_19;
extern unsigned int reg_r2_20;
extern unsigned int reg_r2_21;
extern unsigned int reg_r2_22;
extern unsigned int reg_r2_23;
extern unsigned int reg_r2_24;
extern unsigned int reg_r2_25;
extern unsigned int reg_r2_26;
extern unsigned int reg_r2_27;
extern unsigned int reg_r2_28;
extern unsigned int reg_r2_29;
extern unsigned int reg_r2_30;
extern unsigned int reg_r2_31;
extern unsigned int reg_r2_32;
extern unsigned int reg_r2_33;
extern unsigned int reg_r2_34;
extern unsigned int reg_r2_35;
extern unsigned int reg_r2_36;
extern unsigned int reg_r2_37;
extern unsigned int reg_r2_38;
extern unsigned int reg_r2_39;
extern unsigned int reg_r2_40;
extern unsigned int reg_r2_41;
extern unsigned int reg_r2_42;
extern unsigned int reg_r2_43;
extern unsigned int reg_r2_44;
extern unsigned int reg_r2_45;
extern unsigned int reg_r2_46;
extern unsigned int reg_r2_47;
extern unsigned int reg_r2_48;
extern unsigned int reg_r2_49;
extern unsigned int reg_r2_50;
extern unsigned int reg_r2_51;
extern unsigned int reg_r2_52;
extern unsigned int reg_r2_53;
extern unsigned int reg_r2_54;
extern unsigned int reg_r2_55;
extern unsigned int reg_r2_56;
extern unsigned int reg_r2_57;
extern unsigned int reg_r2_58;
extern unsigned int reg_r2_59;
extern unsigned int reg_r2_60;
extern unsigned int reg_r2_61;
extern unsigned int reg_r2_62;
extern unsigned int reg_r2_63;
extern unsigned int reg_r2_64;
extern unsigned int reg_r2_65;
extern unsigned int reg_r2_66;
extern unsigned int reg_r2_67;
extern unsigned int reg_r2_68;
extern unsigned int reg_r2_69;
extern unsigned int reg_r2_70;
extern unsigned int reg_r2_71;
extern unsigned int reg_r2_72;
extern unsigned int reg_r2_73;
extern unsigned int reg_r2_74;
extern unsigned int reg_r2_75;
extern unsigned int reg_r2_76;
extern unsigned int reg_r2_77;
extern unsigned int reg_r2_78;
extern unsigned int reg_r2_79;
extern unsigned int reg_r2_80;
extern unsigned int reg_r2_81;
extern unsigned int reg_r2_82;
extern unsigned int reg_r2_83;
extern unsigned int reg_r2_84;
extern unsigned int reg_r2_85;
extern unsigned int reg_r2_86;
extern unsigned int reg_r2_87;
extern unsigned int reg_r2_88;
extern unsigned int reg_r2_89;
extern unsigned int reg_r2_90;
extern unsigned int reg_r2_91;
extern unsigned int reg_r2_92;
extern unsigned int reg_r2_93;
extern unsigned int reg_r2_94;
extern unsigned int reg_r2_95;
extern unsigned int reg_r2_96;
extern unsigned int reg_r2_97;
extern unsigned int reg_r2_98;
extern unsigned int reg_r2_99;
extern unsigned int reg_r2_100;
extern unsigned int reg_r2_101;
extern unsigned int reg_r2_102;
extern unsigned int reg_r2_103;
extern unsigned int reg_r2_104;
extern unsigned int reg_r2_105;
extern unsigned int reg_r2_106;
extern unsigned int reg_r2_107;
extern unsigned int reg_r2_108;
extern unsigned int reg_r2_109;
extern unsigned int reg_r2_110;
extern unsigned int reg_r2_111;
extern unsigned int reg_r2_112;
extern unsigned int reg_r2_113;
extern unsigned int reg_r2_114;
extern unsigned int reg_r2_115;
extern unsigned int reg_r2_116;
extern unsigned int reg_r2_117;
extern unsigned int reg_r2_118;
extern unsigned int reg_r2_119;
extern unsigned int reg_r2_120;
extern unsigned int reg_r2_121;
extern unsigned int reg_r2_122;
extern unsigned int reg_r2_123;
extern unsigned int reg_r2_124;
extern unsigned int reg_r2_125;
extern unsigned int reg_r2_126;
extern unsigned int reg_r2_127;
extern unsigned int reg_r3_0;
extern unsigned int reg_r3_1;
extern unsigned int reg_r3_2;
extern unsigned int reg_r3_3;
extern unsigned int reg_r3_4;
extern unsigned int reg_r3_5;
extern unsigned int reg_r3_6;
extern unsigned int reg_r3_7;
extern unsigned int reg_r3_8;
extern unsigned int reg_r3_9;
extern unsigned int reg_r3_10;
extern unsigned int reg_r3_11;
extern unsigned int reg_r3_12;
extern unsigned int reg_r3_13;
extern unsigned int reg_r3_14;
extern unsigned int reg_r3_15;
extern unsigned int reg_r3_16;
extern unsigned int reg_r3_17;
extern unsigned int reg_r3_18;
extern unsigned int reg_r3_19;
extern unsigned int reg_r3_20;
extern unsigned int reg_r3_21;
extern unsigned int reg_r3_22;
extern unsigned int reg_r3_23;
extern unsigned int reg_r3_24;
extern unsigned int reg_r3_25;
extern unsigned int reg_r3_26;
extern unsigned int reg_r3_27;
extern unsigned int reg_r3_28;
extern unsigned int reg_r3_29;
extern unsigned int reg_r3_30;
extern unsigned int reg_r3_31;
extern unsigned int reg_r3_32;
extern unsigned int reg_r3_33;
extern unsigned int reg_r3_34;
extern unsigned int reg_r3_35;
extern unsigned int reg_r3_36;
extern unsigned int reg_r3_37;
extern unsigned int reg_r3_38;
extern unsigned int reg_r3_39;
extern unsigned int reg_r3_40;
extern unsigned int reg_r3_41;
extern unsigned int reg_r3_42;
extern unsigned int reg_r3_43;
extern unsigned int reg_r3_44;
extern unsigned int reg_r3_45;
extern unsigned int reg_r3_46;
extern unsigned int reg_r3_47;
extern unsigned int reg_r3_48;
extern unsigned int reg_r3_49;
extern unsigned int reg_r3_50;
extern unsigned int reg_r3_51;
extern unsigned int reg_r3_52;
extern unsigned int reg_r3_53;
extern unsigned int reg_r3_54;
extern unsigned int reg_r3_55;
extern unsigned int reg_r3_56;
extern unsigned int reg_r3_57;
extern unsigned int reg_r3_58;
extern unsigned int reg_r3_59;
extern unsigned int reg_r3_60;
extern unsigned int reg_r3_61;
extern unsigned int reg_r3_62;
extern unsigned int reg_r3_63;
extern unsigned int reg_r3_64;
extern unsigned int reg_r3_65;
extern unsigned int reg_r3_66;
extern unsigned int reg_r3_67;
extern unsigned int reg_r3_68;
extern unsigned int reg_r3_69;
extern unsigned int reg_r3_70;
extern unsigned int reg_r3_71;
extern unsigned int reg_r3_72;
extern unsigned int reg_r3_73;
extern unsigned int reg_r3_74;
extern unsigned int reg_r3_75;
extern unsigned int reg_r3_76;
extern unsigned int reg_r3_77;
extern unsigned int reg_r3_78;
extern unsigned int reg_r3_79;
extern unsigned int reg_r3_80;
extern unsigned int reg_r3_81;
extern unsigned int reg_r3_82;
extern unsigned int reg_r3_83;
extern unsigned int reg_r3_84;
extern unsigned int reg_r3_85;
extern unsigned int reg_r3_86;
extern unsigned int reg_r3_87;
extern unsigned int reg_r3_88;
extern unsigned int reg_r3_89;
extern unsigned int reg_r3_90;
extern unsigned int reg_r3_91;
extern unsigned int reg_r3_92;
extern unsigned int reg_r3_93;
extern unsigned int reg_r3_94;
extern unsigned int reg_r3_95;
extern unsigned int reg_r3_96;
extern unsigned int reg_r3_97;
extern unsigned int reg_r3_98;
extern unsigned int reg_r3_99;
extern unsigned int reg_r3_100;
extern unsigned int reg_r3_101;
extern unsigned int reg_r3_102;
extern unsigned int reg_r3_103;
extern unsigned int reg_r3_104;
extern unsigned int reg_r3_105;
extern unsigned int reg_r3_106;
extern unsigned int reg_r3_107;
extern unsigned int reg_r3_108;
extern unsigned int reg_r3_109;
extern unsigned int reg_r3_110;
extern unsigned int reg_r3_111;
extern unsigned int reg_r3_112;
extern unsigned int reg_r3_113;
extern unsigned int reg_r3_114;
extern unsigned int reg_r3_115;
extern unsigned int reg_r3_116;
extern unsigned int reg_r3_117;
extern unsigned int reg_r3_118;
extern unsigned int reg_r3_119;
extern unsigned int reg_r3_120;
extern unsigned int reg_r3_121;
extern unsigned int reg_r3_122;
extern unsigned int reg_r3_123;
extern unsigned int reg_r3_124;
extern unsigned int reg_r3_125;
extern unsigned int reg_r3_126;
extern unsigned int reg_r3_127;
