#!/usr/bin/perl
##
## Copyright (C) 2007 Hewlett-Packard Company
##
## The information and source code contained herein is the exclusive
## property of Hewlett-Packard Company and may not be reproduced 
## in whole or in part without explicit written authorization from 
## the company. See "<vexroot>/LICENSE.txt" for license terms.
##

#
# $Id: runreport,v 1.3 2007/01/25 09:21:49 frb Exp $
#
use strict;

my %STAT;
my %WIDTH;
my @LOGS;
my $NCHART=0;

for my $arg (@ARGV) {
	my $ln = $arg; $ln =~ s/ta.log.//;
    parseLog($arg,$ln);
}
emitReport();

exit 0;

sub parseLog {
    my $log = shift;
	my $ln = shift;
	push @LOGS, $ln;
	open FH, "<$log";
	while (<FH>) {
		chomp;
		s/[)(]//g;
		my @fields = split(/[\s]+/);
	    if    (/Total Cycles:/)         { $STAT{$ln}{'Total'} = $fields[2]; 
	                                      $STAT{$ln}{'Time'} = $fields[3]; }
		elsif (/Execution Cycles:/)     { $STAT{$ln}{'Execution'} =  $fields[2]; }
		elsif (/Stall Cycles:/)         { $STAT{$ln}{'Stall'}  = $fields[2]; }
		elsif (/Nops:/)                 { $STAT{$ln}{'Nops'} = $fields[1]; }
		elsif (/Executed operations:/)  { $STAT{$ln}{'Ops'} = $fields[2]; }
		elsif (/Avg. IPC.*no stalls:/)  { $STAT{$ln}{'IPCfunc'} = $fields[4]; }
		elsif (/Avg. IPC.*with stalls:/){ $STAT{$ln}{'IPCtot'} = $fields[4]; }
		elsif (/width\[ ([0-9]*)\]/)    { $WIDTH{$ln}{"$1"} = $fields[4]; }
	}
	close FH;
}

sub emitReport {
	emitHead();
	emitTableHead();

	emitMetric('Time',"%.3f");
	emitMetric('Total',"%d");
	emitMetric('Execution',"%d");
	emitMetric('Stall',"%d");
	emitMetric('Nops',"%d");
	emitMetric('Ops',"%d");
	print "\n";
	emitMetric('IPCfunc',"%.2f");
	emitMetric('IPCtot',"%.2f");

	emitTableTail();

	plotMetric('Time');
	plotMetric('IPCfunc','IPCtot');
	foreach my $log (@LOGS) {
	    print "<p>";print "Run $log"; print "</p>\n";
		print "<table><tr><td>\n";
	    plotPie($log, 'Execution','Stall','Nops');
		print "</td><td>\n";
	    plotWidth($log);
		print "</td></tr></table>\n";
	}
	emitTail();
}

sub emitHead {
    print <<__EOF__;
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>VEX report</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<script src="web/mochi/MochiKit.js" type="text/javascript"></script>
<script src="web/plotkit/excanvas.js" type="text/javascript"></script>
<script src="web/plotkit/PlotKit_Packed.js" type="text/javascript"></script>
</head>
<body>
__EOF__
}

sub emitTail { print "</body></html>\n"; }

sub emitTableHead { 
    print "<table id=\"stats\" class=\"data\">\n";
    print "<thead><tr><td></td>";
	foreach my $log (@LOGS) { print "<td>$log</td> "; }
    print "</tr></thead>\n";
    print "<tbody>\n";
}

sub emitTableTail { print "</tbody>\n</table>\n"; }

sub emitMetric {
    my $m = shift; # metric
    my $f = shift; # format
	printf "<tr><td>%s</td>", $m; 
	foreach my $log (@LOGS) {
	    printf "<td>$f</td>", $STAT{$log}{$m}; 
	}
	print "</tr>\n";
}

sub plotMetric {
	$NCHART++;
	my $chart = "chart$NCHART";
    for my $m (@_) { print "$m "; }
    print "<div id=\"$chart\" style=\"margin: 0 0 0 0;\" width=\"500\" height=\"200\"></div>\n";
    print "<script type=\"text/javascript\">\n";
	my $i = 0;
    for my $m (@_) {
	    my $x = 0;
	    my $dataset = "";
	    foreach my $log (@LOGS) {
		    my $v = $STAT{$log}{$m}; 
		    $dataset .= ($x>0 ? ", ":"") . "[$x,$v]";
		    $x++;
	    }
        print("  var data$i = [$dataset];\n");
		$i++;
    }
    print("  var plotter = EasyPlot(\"bar\", {}, \$(\"$chart\"), ["); 
	for (my $n=0; $n<$i; $n++) { print $n>0?",":"","data$n"; }
	print "]);\n";
    print("</script>\n</div>\n");
}

sub plotPie {
	$NCHART++;
	my $log = shift;
	my $chart = "chart$NCHART";


    print "<div id=\"$chart\" style=\"margin: 0 0 0 0;\" width=\"200\" height=\"200\"></div>\n";
    print "<script type=\"text/javascript\">\n";

	my $x = 0;
	my $dataset = "";
	my $xticks = "";
    for my $m (@_) {
		my $v = $STAT{$log}{$m}; 
		$xticks .= ($x>0 ? ", ":"") . "{label:\"$m\",v:$x}";
		$dataset .= ($x>0 ? ", ":"") . "[$x,$v]";
		$x++;
    }
    print("  var option = {\"xTicks\":[$xticks]};\n");
    print("  var data = [$dataset];\n");
    print("  var plotter = EasyPlot(\"pie\", option, \$(\"$chart\"), [data]);\n"); 
    print("</script>\n</div>\n");
}

sub plotWidth {
	$NCHART++;
	my $log = shift;
	my $chart = "chart$NCHART";
    print "<div id=\"$chart\" style=\"margin: auto auto auto auto;\" width=\"200\" height=\"200\"></div>\n";
    print "<script type=\"text/javascript\">\n";

	my $dataset = "";
	my $x = 0;
    for my $m (sort keys %{$WIDTH{$log}}) {
		my $v = $WIDTH{$log}{$m}; 
		$dataset .= ($x>0 ? ", ":"") . "[$m,$v]";
		$x++;
    }
    print("  var data = [$dataset];\n");
    print("  var plotter = EasyPlot(\"pie\", {}, \$(\"$chart\"), [data]);\n"); 
    print("</script>\n</div>\n");
}
