/**
*** Copyright (C) 1995-2005 Hewlett-Packard Company.
*** See "LICENSE.txt" for license terms
**/

#include <stdio.h>
#include "imgpipe.h"
#include "wppm.h"

#define CMYK_CONTONE

static char *magic = "P6";	/* PPM binary */
static ubyte maxcolor = 255;

extern void open_ppm(int width, int height, FILE * fp)
{
    fprintf(fp, "%s\n", magic);
    fprintf(fp, "# Generated by imgpipe\n");
    fprintf(fp, "%ld %ld\n", (int) width, (int) height);
    fprintf(fp, "%d\n", maxcolor);
}

extern void write_ppm_row(ubyte * linedata, int width, FILE * fp)
{
    const ubyte *pc, *pm, *py, *pk;
    ubyte *pr, *pg, *pb;
    int i;

    // { static int row = 0; printf("row %d\n", row++); }

    pc = linedata;
    pm = linedata + 1;
    py = linedata + 2;
    pk = linedata + 3;

    pr = linedata;
    pg = linedata + 1;
    pb = linedata + 2;

    for (i = 0; i < width; ++i) {
#if defined(CMYK_CONTONE)
	ubyte k = *pk;
	ubyte r = 255 - *pc;
	ubyte g = 255 - *pm;
	ubyte b = 255 - *py;
	r = r - k;
	g = g - k;
	b = b - k;
	*pr = r;
	*pg = g;
	*pb = b;
	pc += 4;
	pm += 4;
	py += 4;
	pk += 4;
	pr += 3;
	pg += 3;
	pb += 3;
#else /* RGB */
	*pr = *pc;
	*pg = *pm;
	*pb = *py;
	pc += 3;
	pm += 3;
	py += 3;
	pr += 3;
	pg += 3;
	pb += 3;
#endif
    }
    fwrite(linedata, 1, 3 * width, fp);
}

extern void close_ppm(FILE * fp)
{
}

